name: Build and deploy JAR app to Azure Web App - app-achievepeak-api  
  
on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    permissions:  
      contents: read # This is required for actions/checkout  
    steps:  
      - uses: actions/checkout@v4  
      - name: Set up Java version  
        uses: actions/setup-java@v4  
        with:  
          java-version: '21'  # 올바른 SemVer 표기법 사용  
          distribution: 'microsoft'  
      - name: Grant execute permission for gradlew  
        run: chmod +x ./gradlew  
        working-directory: achievepeak  # Gradle 프로젝트 디렉토리 설정  
      - name: Build with Gradle  
        run: ./gradlew clean build  
        working-directory: achievepeak  # Gradle 프로젝트 디렉토리 설정  
      - name: Upload artifact for deployment job  
        uses: actions/upload-artifact@v4  
        with:  
          name: java-app  
          path: 'achievepeak/build/libs/*.jar'  # 빌드 결과물 경로 설정  
  
  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
    environment:  
      name: 'Production'  
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  
    permissions:  
      id-token: write # This is required for requesting the JWT  
      contents: read # This is required for actions/checkout  
    steps:  
      - name: Download artifact from build job  
        uses: actions/download-artifact@v4  
        with:  
          name: java-app  
          path: ./  # 현재 디렉토리에 아티팩트 다운로드  
      - name: List files in current directory for debugging  
        run: ls -al  
      - name: Move downloaded artifact to target directory  
        run: |  
          JAR_FILE=$(ls *.jar | head -n 1)  
          echo "Found JAR file: $JAR_FILE"  
          mv "$JAR_FILE" app.jar  
      - name: Login to Azure  
        uses: azure/login@v2  
        with:  
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0BACB4ABA44C4B5D863DEEAD1AF62DB8 }}  
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4CA0B4397A4048E3B32360DD867D2D35 }}  
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4113545AFA9E4CFAB9881EEAA82A5BA9 }}  
      - name: Deploy to Azure Web App  
        id: deploy-to-webapp  
        uses: azure/webapps-deploy@v3  
        with:  
          app-name: 'app-achievepeak-api'  
          slot-name: 'Production'  
          package: 'app.jar'  # 특정 파일 지정  
